version: "3"

services:
  client:
    image: node:12
    command: "yarn run start"
    working_dir: /app/react-redux/client
    stdin_open: true
    volumes:
      - ".:/app"
    environment:
      - PORT=8080
      - NODE_ENV=production
    ports:
      - "8080:8080"
