version: "3"

services:
  cypress:
    build:
      context: ./tests
      dockerfile: Dockerfile
    command: tail -f /dev/null # avoid container from stopping in order to run "docker-compose exec cypress"
    depends_on:
      - client
      - api
    volumes:
      - ./tests:/app
    working_dir: /app
    links:
      - "client:client"
      - "api:api"

  client:
    environment:
      - REACT_APP_API_ROOT=http://api:4000/api
      - PORT=4100
      - NODE_ENV=production
