version: "3"

services:
  cypress:
    image: cypress/included:5.1.0
    depends_on:
      - client
      - api
    volumes:
      - ./tests:/app
    working_dir: /app
    links:
      - "client:client"
      - "api:api"

  client:
    environment:
      - REACT_APP_API_ROOT=http://api:4000/api
      - PORT=4100
      - NODE_ENV=production
