version: "3"

services:
  client:
    image: node:12
    command: "yarn run start"
    working_dir: /app/client
    stdin_open: true
    volumes:
      - ".:/app"
    environment:
      - REACT_APP_API_ROOT=http://localhost:4000/api
      - PORT=4100
      - NODE_ENV=production
    ports:
      - "4100:4100"

  api:
    image: node:12
    command: "yarn run start"
    working_dir: /app/api
    volumes:
      - ".:/app"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - SECRET=conduit
      - MONGODB_URI=mongodb://mongo:27027/conduit
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --port 27027 --storageEngine=wiredTiger
    ports:
      - 27027:27027
    volumes:
      - ./tests/data:/data
